// Actions
export const SESSION_CONNECT_WEB3 = 'SESSION_CONNECT_WEB3'

export const CONTROLLER_MARKET_UPDATE_BORROW_RATE = 'CONTROLLER_MARKET_UPDATE_BORROW_RATE'
export const CONTROLLER_MARKET_GET_BORROW_RATE = 'CONTROLLER_MARKET_GET_BORROW_RATE'
export const CONTROLLER_MARKET_GET_CASH = 'CONTROLLER_MARKET_GET_CASH'
export const CONTROLLER_MARKET_GET_TOTAL_BORROWS = 'CONTROLLER_MARKET_GET_TOTAL_BORROWS'
export const CONTROLLER_MARKET_GET_TOTAL_SUPPLIES = 'CONTROLLER_MARKET_GET_TOTAL_SUPPLIES'
export const CONTROLLER_MARKET_UPDATE = 'CONTROLLER_MARKET_UPDATE'

// Mutations
export const SESSION_SET_PROPERTY = 'SESSION_SET_PROPERTY'
export const DRAWER_SET = 'DRAWER_SET'
export const DRAWER_SET_DATA = 'DRAWER_SET_DATA'
export const DRAWER_SET_PROPERTY = 'DRAWER_SET_PROPERTY'

export const CONTROLLER_SET_PROPERTY = 'CONTROLLER_SET_PROPERTY'
export const CONTROLLER_SET_MARKET_TOKEN_ADDRESS = 'CONTROLLER_SET_MARKET_TOKEN_ADDRESS'
export const CONTROLLER_SET_MARKET_TOKEN_NAME = 'CONTROLLER_SET_MARKET_TOKEN_NAME'
export const CONTROLLER_SET_MARKET_TOKEN_SYMBOL = 'CONTROLLER_SET_MARKET_TOKEN_SYMBOL'
export const CONTROLLER_SET_MARKET_TOKEN_DECIMALS = 'CONTROLLER_SET_MARKET_TOKEN_DECIMALS'
export const CONTROLLER_SET_MARKET_CASH = 'CONTROLLER_SET_MARKET_CASH'
export const CONTROLLER_SET_MARKET_PRICE = 'CONTROLLER_SET_MARKET_PRICE'
export const CONTROLLER_SET_MARKET_BORROW_RATE = 'CONTROLLER_SET_MARKET_BORROW_RATE'
export const CONTROLLER_SET_MARKET_TOTAL_BORROWS = 'CONTROLLER_SET_MARKET_TOTAL_BORROWS'
export const CONTROLLER_SET_MARKET_TOTAL_SUPPLIES = 'CONTROLLER_SET_MARKET_TOTAL_SUPPLIES'
export const CALCULATE_APR = 'CALCULATE_APR'

export const SNACK_SET = 'SNACK_SET'
export const SNACK_SET_SUCCESS_TX = 'SNACK_SET_SUCCESS_TX'
export const SNACK_SET_SUCCESS_APPROVE_TX = 'SNACK_SET_SUCCESS_APPROVE_TX'
export const SNACK_SET_FAIL_TX = 'SNACK_SET_FAIL_TX'
export const SNACK_SET_WAIT_TX = 'SNACK_SET_WAIT_TX'
export const SNACK_GENERAL_SET = 'SNACK_GENERAL_SET'

// Getters
export const SESSION_IS_LOGGED = 'SESSION_IS_LOGGED'
export const PERIOD_DAY = 'day'
export const PERIOD_MONTH = 'month'
export const PERIOD_WEEK = 'week'
export const PERIOD_YEAR = 'year'
